name: Java CI Alessia

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn package -DskipTests

      # Update dependency graph
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
        with:
          token: ${{ secrets.ACTIONS_TOKEN_BOOKKEEPER }}
        if: always() # Assicura che questo passaggio venga eseguito anche se i passaggi precedenti falliscono

      # Handle errors
      - name: Handle errors
        if: ${{ failure() }}
        run: echo "An error occurred while updating the dependency graph."
